# ==================== #
# Project Details
# ==================== #
name: 'dbt_ga4_project'
version: '1.0.0'
config-version: 2
profile: 'default' # 
# require-dbt-version: <dbt_version> #

# ==================== #
# File Path Configs
# ==================== #
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]
target-path: "target" # directory which will store compiled SQL files
clean-targets:        # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# ==================== #
# Run Hooks
# ==================== #
# on-run-start:
#   - "<run_on_start>"

# on-run-end:
#   - "<run_on_end>"

# ==================== #
# Variable Configs
# ==================== #
vars:
  project: "bigquery-public-data"
  dataset: "ga4_obfuscated_sample_ecommerce"
  start_date: "20210120" ## CHANGE TO YYYY-MM-DD FORMAT AND SWITCH CASTING IN BASE MODEL ##

# TESTING SOME VARS:
  excluded_events: []
  excluded_event_params: ['ga_session_id', 'page_location', 'ga_session_number', 'session_engaged', 'engagement_time_msec', 'page_title', 'page_referrer', 'source', 'medium', 'campaign', 'debug_mode', 'term', 'clean_event', 'value', 'tax', 'coupon', 'promotion_name']
  excluded_user_props: []

########################TO DO##############################
# Query parameter exclusions
# You can remove specific query parameters from the page_location by listing them here
#    query_parameter_exclusions: ["gclid","fbclid","_ga"]

# User Properties
# User-scoped event properties can be assigned using the following variable configuration in your dbt_project.yml
# The dim_ga4__users dimension table will be updated to include the last value seen for each user
#      user_properties:
#        - event_parameter: "page_location"
#          user_property_name: "most_recent_page_location"  
#          value_type: "string_value"
#        - event_parameter: "another_event_param"
#          user_property_name: "most_recent_param"  
#          value_type: "string_value"

# Custom parameters
# custom parameters are registered by creating a var matching the event name where the custom parameter occurs
# and providing the name, matching the parameters name
# and matching the value_type to the type of column in BigQuery (string_value, int_value, float_value, double_value)
# the below example shows a page_view enhanced with the clean_event event parameter from the ga4_obfuscated_sample_ecommerce project
#    page_view:
#      - name: "clean_event"
#        value_type: "string_value"  
########################TO DO##############################


# ==================== #
# Model Configs
# ==================== #
models:
  dbt_ga4_project:
    +materialized: view
    marts:
      +materialized: table  